version: '3.8'

services:

  db:
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_backend_eventstore_dev
    ports:
      - '5432:5432'
